# Generated by Django 5.1.6 on 2025-02-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('insurance_company', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('model', models.CharField(max_length=100)),
                ('zd', models.FloatField(blank=True, null=True)),
                ('con', models.FloatField(blank=True, null=True)),
                ('engine', models.FloatField(blank=True, null=True)),
                ('tyre', models.FloatField(blank=True, null=True)),
                ('rti', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
